[package]
type = 'app'
name = 'bake'
slug = 'bake'
version = '1.8.2'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'A Bash-based Make alternative'

[run]
dependencies = ['https://github.com/hyperupcall/bats-all.git@v4.2.0']
binDirs = ['pkg/bin']

[run.setOptions]
errexit = 'on'
pipefail = 'on'

[run.shoptOptions]
shift_verbose = 'on'
